name: Copy XCFramework from Private to Public Repo

on:
  workflow_dispatch:  # Manually triggered for demonstration; you can customize this trigger

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repository
        uses: actions/checkout@v2
        with:
          repository: vivektechyogi/arithmetic-operations
          token: ${{ secrets.GITHUB_TOKEN }}
          path: public-repo

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone private repository
        run: |
          git clone git@github.com:SwiftPackageManagerDemo/Addition.git private-repo
          cd private-repo
          git checkout main

      - name: Copy XCFramework to Public Repo
        run: |
          cp private-repo/Framework/Addition.xcframework.zip public-repo/

      - name: Configure Git
        run: |
          cd public-repo
          git config --global user.email "iamviveklalan@gmail.com"
          git config --global user.name "Vivek Lalan"

      - name: Commit and Push to Public Repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd public-repo
          git add Framework/Addition.xcframework.zip
          git commit -m "Add Addition.xcframework.zip"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/vivektechyogi/arithmetic-operations.git main
