name: Update Checksum and Link

on:
  repository_dispatch:
    types: [update-checksum]

jobs:
  update-files:
    name: Update Checksum and Link
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update Package.swift
      run: |
        VERSION="${{ github.event.client_payload.version }}"
        CHECKSUM="${{ github.event.client_payload.checksum }}"
        URL="${{ github.event.client_payload.url }}"

        # Assuming the link and checksum are in Package.swift or another known file
        sed -i '' -e "s|url: .*|url: \"$URL\",|" -e "s|checksum: .*|checksum: \"$CHECKSUM\"|" Package.swift

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@users.noreply.github.com'
        git add Package.swift
        git commit -m "Update framework to $VERSION"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
