name: Copy XCFramework from Private to Public Repo

on:
  workflow_dispatch:  # Manually triggered for demonstration; you can customize this trigger

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repository
        uses: actions/checkout@v2
        with:
          repository: vivektechyogi/arithmetic-operations
          token: ${{ secrets.GITHUB_TOKEN }}
          path: public-repo

      - name: Clone private repository
        run: |
          git clone https://github.com/SwiftPackageManagerDemo/Addition.git private-repo
          cd private-repo
          git checkout main
        env:
          PAT: ${{ secrets.PAT }}

      - name: Copy XCFramework to Public Repo
        run: |
          cp private-repo/Framework/Addition.xcframework.zip public-repo/Framework/

      - name: Commit and Push to Public Repo
        run: |
          cd public-repo
          git add Framework/Addition.xcframework.zip
          git commit -m "Add Addition.xcframework.zip"
          git push https://github-actions:${{ secrets.PAT }}@github.com/vivektechyogi/arithmetic-operations.git main
