name: Download and Commit Framework

on:
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Change to Project Directory
      run: cd $GITHUB_WORKSPACE

    - name: Verify Zip Checksum
      run: |
          local_checksum=$(sha256sum EsVoiceCall/EsVoiceCall.xcframework.zip | awk '{print $1}')
          echo "Local Zip Checksum: $local_checksum"
          
    - name: Download Framework
      run: |
        mkdir -p EsVoiceCall
        curl -L -o EsVoiceCall/EsVoiceCall.xcframework.zip https://es-sc-ios-sdk.s3.ap-southeast-2.amazonaws.com/EsVoiceCall/EsVoiceCall.xcframework.zip


    - name: Get New Downloaded Zip Checksum
      run: |
          remote_checksum=$(sha256sum EsVoiceCall/EsVoiceCall.xcframework.zip | awk '{print $1}')
          echo "Remote Zip Checksum: $remote_checksum"

    - name: Compare Checksums
      id: compare
      run: |
          if [ "${{ steps.download-and-commit.outputs.local_checksum }}" != "${{ steps.download-and-commit.outputs.remote_checksum }}" ]; then
            echo "Checksums are different."
            echo "::set-output name=different_checksums::true"
          else
            echo "Checksums are the same."
            echo "::set-output name=different_checksums::false"
          fi

    - name: Configure Git
      run: |
        git config --global user.name 'Vivek Lalan'
        git config --global user.email 'iamviveklalan@gmail..com'
        
    - name: Add to Git and Commit
      run: |
        git pull
        git add EsVoiceCall/EsVoiceCall.xcframework.zip
        git commit -m "Add downloaded framework zip file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
