name: Download and Commit Framework

on:
  workflow_dispatch:

jobs:
  download_commit_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download xcframework zip
      run: wget -O framework/EsVoiceCall.xcframework.zip https://es-sc-ios-branding-sdk.s3.ap-southeast-2.amazonaws.com/EsVoiceCall/EsVoiceCall.xcframework.zip

    - name: Unzip the framework
      run: |
        mkdir -p framework
        unzip framework/EsVoiceCall.xcframework.zip -d framework/
        rm framework/EsVoiceCall.xcframework.zip

    - name: Commit changes
      run: |
        git add framework/
        git commit -m "Add downloaded xcframework"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push
